"""empty message

Revision ID: 074e27a95739
Revises: 42eb7cace03d
Create Date: 2022-05-02 11:52:18.987652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '074e27a95739'
down_revision = '42eb7cace03d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Eventos', sa.Column('grupo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Eventos', 'grupo')
    # ### end Alembic commands ###
