"""empty message

Revision ID: 0825820c95dc
Revises: f605a03ebf38
Create Date: 2022-04-28 11:53:26.913547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0825820c95dc'
down_revision = 'f605a03ebf38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GruposTEMP', sa.Column('owner', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('GruposTEMP', 'owner')
    # ### end Alembic commands ###
