"""empty message

Revision ID: 42eb7cace03d
Revises: 4b4e32c13e2a
Create Date: 2022-05-02 09:16:24.440229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42eb7cace03d'
down_revision = '4b4e32c13e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Grupo_User_Relation',
    sa.Column('grupo', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('admin', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('grupo', 'user')
    )
    op.drop_column('GruposTEMP', 'members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GruposTEMP', sa.Column('members', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_table('Grupo_User_Relation')
    # ### end Alembic commands ###
