"""empty message

Revision ID: 5d2fe2cab8e5
Revises: 0825820c95dc
Create Date: 2022-04-28 16:24:25.256250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2fe2cab8e5'
down_revision = '0825820c95dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GruposTEMP',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GruposTEMP')
    # ### end Alembic commands ###
