"""empty message

Revision ID: 95677f71203f
Revises: 074e27a95739
Create Date: 2022-05-02 16:00:25.000259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95677f71203f'
down_revision = '074e27a95739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Grupos',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_table('GruposTEMP')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GruposTEMP',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='GruposTEMP_pkey')
    )
    op.drop_table('Grupos')
    # ### end Alembic commands ###
