"""empty message

Revision ID: bb35967fea04
Revises: 22650f69abe1
Create Date: 2022-04-29 18:30:34.197656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb35967fea04'
down_revision = '22650f69abe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GruposTEMP',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('members', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GruposTEMP')
    # ### end Alembic commands ###
