"""empty message

Revision ID: c373c801cbb0
Revises: 95677f71203f
Create Date: 2022-05-12 10:35:28.357100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c373c801cbb0'
down_revision = '95677f71203f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Eventos', 'Grupos', ['grupo'], ['name'])
    op.create_foreign_key(None, 'Grupo_User_Relation', 'Usuarios', ['user'], ['name'])
    op.create_foreign_key(None, 'Grupo_User_Relation', 'Grupos', ['grupo'], ['name'])
    op.create_foreign_key(None, 'Grupos', 'Usuarios', ['owner'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Grupos', type_='foreignkey')
    op.drop_constraint(None, 'Grupo_User_Relation', type_='foreignkey')
    op.drop_constraint(None, 'Grupo_User_Relation', type_='foreignkey')
    op.drop_constraint(None, 'Eventos', type_='foreignkey')
    # ### end Alembic commands ###
