"""empty message

Revision ID: e0a1fed237bb
Revises: 140d85a17f98
Create Date: 2022-05-07 12:37:38.495744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a1fed237bb'
down_revision = '140d85a17f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Eventos_grupo_fkey', 'Eventos', type_='foreignkey')
    op.drop_constraint('Grupo_User_Relation_user_fkey', 'Grupo_User_Relation', type_='foreignkey')
    op.drop_constraint('Grupo_User_Relation_grupo_fkey', 'Grupo_User_Relation', type_='foreignkey')
    op.drop_constraint('Grupos_owner_fkey', 'Grupos', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('Grupos_owner_fkey', 'Grupos', 'Usuarios', ['owner'], ['name'])
    op.create_foreign_key('Grupo_User_Relation_grupo_fkey', 'Grupo_User_Relation', 'Grupos', ['grupo'], ['name'])
    op.create_foreign_key('Grupo_User_Relation_user_fkey', 'Grupo_User_Relation', 'Usuarios', ['user'], ['name'])
    op.create_foreign_key('Eventos_grupo_fkey', 'Eventos', 'Grupos', ['grupo'], ['name'])
    # ### end Alembic commands ###
